from pathlib import Path
p=Path('/mnt/data/work2')
index=(p/'index.html').read_text()
# CSS
index=index.replace('.page{max-width:560px;margin:auto;padding:22px 16px 90px}.wallet-head{margin:6px 2px 12px}.wallet-head h1{font-size:19px;margin:0}', '.page{max-width:560px;margin:auto;padding:18px 14px 90px}.brand-head{display:flex;align-items:center;justify-content:center;gap:12px;margin:4px 0 16px;text-align:right}.brand-head img{width:58px;height:58px;object-fit:contain;background:#fffaf0;border:1px solid var(--line);border-radius:16px;padding:5px;box-shadow:0 8px 20px #5a3e1b10}.brand-head h1{font-size:21px;line-height:1.25;margin:0}.brand-head p{font-size:10px;color:var(--muted);margin:3px 0 0}')
index=index.replace('.wallet-card{position:relative;overflow:hidden;border-radius:22px;background:linear-gradient(145deg,#e7b64f,#d9a441 55%,#b87520);color:#2b2118;box-shadow:0 16px 34px #4b321d35;border:1px solid #d5a95855;height:410px;padding:17px}', '.wallet-card{position:relative;overflow:hidden;border-radius:20px;background:linear-gradient(145deg,#e7b64f,#d9a441 55%,#b87520);color:#2b2118;box-shadow:0 14px 28px #4b321d30;border:1px solid #d5a95855;min-height:355px;padding:15px}')
index=index.replace('.mini-brand img{width:50px;height:50px;object-fit:contain;border-radius:12px;background:#fff;padding:4px;box-shadow:0 4px 12px #6b4c2420}.mini-brand div{direction:rtl;text-align:right}\n.mini-brand strong{display:block;font-size:14px}.mini-brand span{font-size:9px;color:#5b3b18}.card-user{margin-top:18px}', '.mini-brand img{width:42px;height:42px;object-fit:contain;border-radius:10px;background:#fff;padding:3px;box-shadow:0 4px 12px #6b4c2420}.mini-brand div{direction:rtl;text-align:right}.mini-brand strong{display:block;font-size:13px}.mini-brand span{font-size:8px;color:#5b3b18}.card-user{margin-top:13px}')
index=index.replace('.customer-name{font-size:20px;font-weight:800}', '.customer-name{font-size:18px;font-weight:800}')
index=index.replace('.progress-row{display:flex;justify-content:space-between;align-items:end;margin:15px 0 7px}', '.progress-row{display:flex;justify-content:space-between;align-items:end;margin:11px 0 6px}')
index=index.replace('.stamps{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:14px}', '.stamps{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:11px}')
index=index.replace('.stamp{aspect-ratio:1;border-radius:50%;', '.stamp{aspect-ratio:1;min-width:0;border-radius:50%;')
index=index.replace('.card-bottom{margin-top:12px;', '.card-bottom{margin-top:9px;')
index=index.replace('.manager-link{display:block;text-align:center;margin-top:10px;padding:11px;border-radius:14px;background:#fffaf0;border:1px solid var(--line);color:#4b3621;text-decoration:none;font-weight:800;font-size:12px}', '.store-link{display:block;text-align:center;margin-top:11px;padding:12px;border-radius:14px;background:linear-gradient(135deg,#e7b64f,#b87520);color:#24170c;text-decoration:none;font-weight:900;font-size:12px;box-shadow:0 8px 18px #5a3e1b18}.store-link:active{transform:translateY(1px)}')
index=index.replace('@media(max-width:390px){.page{padding:16px 11px 90px}.wallet-card{height:395px;padding:15px}.features{gap:5px}.feature{padding:9px 4px}}', '@media(max-width:390px){.page{padding:15px 10px 90px}.brand-head img{width:52px;height:52px}.brand-head h1{font-size:19px}.wallet-card{min-height:345px;padding:13px}.features{gap:5px}.feature{padding:9px 4px}.stamp{font-size:10px}}')
# Header
index=index.replace('<div class="wallet-head"><h1>محفظتك خاتم هدايا</h1></div>\n<article class="wallet-card">','<div class="brand-head"><img id="brandLogo" src="assets/logo.svg" alt="الشعار"><div><h1 id="brandTitle">مناحل شيخ الجبل</h1><p id="brandSubtitle">العسل الحضرمي</p></div></div>\n<article class="wallet-card">')
index=index.replace('<a class="manager-link" href="admin.html">🔐 صفحة المدير</a>','<a class="store-link hidden" id="storeLink" href="#" target="_blank" rel="noopener">🛍️ متجر مناحل شيخ الجبل</a>')
# defaults
index=index.replace("let data={name:'عميل',phone:'',stamps:0},settings={totalStamps:10,cardTitle:'مناحل شيخ الجبل',cardSubtitle:'للعسل الحضرمي الدوعني',giftText:'10 أختام = هدية 🎁',logoUrl:'assets/logo.svg',stampUrl:'',cardStart:'#e7b64f',cardEnd:'#b87520'},stop=null;", "let data={name:'عميل',phone:'',stamps:0},settings={totalStamps:10,cardTitle:'مناحل شيخ الجبل',cardSubtitle:'العسل الحضرمي',giftText:'10 أختام = هدية 🎁',logoUrl:'assets/logo.svg',stampUrl:'',storeUrl:'',cardStart:'#e7b64f',cardEnd:'#b87520'},stop=null;")
# draw additions
old="$('cardLogo').src=settings.logoUrl||'assets/logo.svg';document.querySelector('.wallet-card').style.background=`linear-gradient(145deg,${settings.cardStart||'#e7b64f'},${settings.cardEnd||'#b87520'})`;$('cardTitle').textContent=settings.cardTitle||'مناحل شيخ الجبل';$('cardSubtitle').textContent=settings.cardSubtitle||'للعسل الحضرمي الدوعني';$('giftLabel').textContent=(settings.giftText||`${total} أختام = هدية 🎁`).replace(/\d+/,total);"
new="$('cardLogo').src=settings.logoUrl||'assets/logo.svg';$('brandLogo').src=settings.logoUrl||'assets/logo.svg';document.querySelector('.wallet-card').style.background=`linear-gradient(145deg,${settings.cardStart||'#e7b64f'},${settings.cardEnd||'#b87520'})`;$('cardTitle').textContent=settings.cardTitle||'مناحل شيخ الجبل';$('cardSubtitle').textContent=settings.cardSubtitle||'العسل الحضرمي';$('brandTitle').textContent=settings.cardTitle||'مناحل شيخ الجبل';$('brandSubtitle').textContent=settings.cardSubtitle||'العسل الحضرمي';$('giftLabel').textContent=(settings.giftText||`${total} أختام = هدية 🎁`).replace(/\d+/,total);const store=$('storeLink');if(settings.storeUrl){store.href=settings.storeUrl;store.classList.remove('hidden')}else{store.href='#';store.classList.add('hidden')}"
index=index.replace(old,new)
(p/'index.html').write_text(index)

admin=(p/'admin.html').read_text()
admin=admin.replace('.page{max-width:720px;margin:auto;padding:22px 16px 45px}', '.page{max-width:720px;margin:auto;padding:18px 14px 45px}')
admin=admin.replace('.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}', '.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.settings-grid label{display:block;font-size:12px;font-weight:700;color:#5d4a38}.store-field{grid-column:1/-1}')
admin=admin.replace('<label>نص الهدية<input class="field" id="giftText" placeholder="10 أختام = هدية 🎁"></label>', '<label>نص الهدية<input class="field" id="giftText" placeholder="10 أختام = هدية 🎁"></label><label class="store-field">رابط المتجر الإلكتروني<input class="field" id="storeUrl" type="url" placeholder="https://example.com"></label>')
admin=admin.replace('src="../assets/logo.svg"','src="assets/logo.svg"')
admin=admin.replace("const ADMIN_UID='DPOfZKEEhogjxeEgoKijthen7gZ2', $=x=>document.getElementById(x);let customers=[],settings={totalStamps:10,cardTitle:'مناحل شيخ الجبل',cardSubtitle:'للعسل الحضرمي الدوعني',giftText:'10 أختام = هدية 🎁',logoUrl:'assets/logo.svg',stampUrl:'',cardStart:'#e7b64f',cardEnd:'#b87520'};", "const ADMIN_UID='DPOfZKEEhogjxeEgoKijthen7gZ2', ADMIN_EMAIL='a777052026@gmail.com', $=x=>document.getElementById(x);let customers=[],settings={totalStamps:10,cardTitle:'مناحل شيخ الجبل',cardSubtitle:'العسل الحضرمي',giftText:'10 أختام = هدية 🎁',logoUrl:'assets/logo.svg',stampUrl:'',storeUrl:'',cardStart:'#e7b64f',cardEnd:'#b87520'};")
admin=admin.replace("c==='permission-denied'?'لا توجد صلاحية'", "c==='permission-denied'?'لا توجد صلاحية لحفظ البيانات'")
admin=admin.replace("import{collection,getDocs,doc,updateDoc,getDoc,setDoc}from", "import{collection,getDocs,doc,updateDoc,getDoc,setDoc,serverTimestamp}from")
admin=admin.replace("$('giftText').value=settings.giftText||'';$('cardStart').value", "$('giftText').value=settings.giftText||'';$('storeUrl').value=settings.storeUrl||'';$('cardStart').value")
admin=admin.replace("if(u&&u.uid===ADMIN_UID)", "if(u&&(u.uid===ADMIN_UID || (u.email||'').toLowerCase()===ADMIN_EMAIL))")
old="settings={...settings,logoUrl,stampUrl,cardTitle:$('cardTitle').value.trim()||'مناحل شيخ الجبل',cardSubtitle:$('cardSubtitle').value.trim()||'للعسل الحضرمي الدوعني',totalStamps:total,giftText:gift,cardStart:$('cardStart').value,cardEnd:$('cardEnd').value,updatedAt:new Date()};\n await setDoc(doc(db,'settings','site'),settings,{merge:true});$('logoFile').value='';$('stampFile').value='';await loadSettings();render();toast('تم حفظ إعدادات البطاقة')"
new="const rawStore=$('storeUrl').value.trim();let storeUrl='';if(rawStore){try{const u=new URL(rawStore);if(!/^https?:$/.test(u.protocol))throw new Error('bad');storeUrl=u.href}catch(_){toast('رابط المتجر غير صحيح، استخدم https:// أو http://');return}}\n settings={...settings,logoUrl,stampUrl,cardTitle:$('cardTitle').value.trim()||'مناحل شيخ الجبل',cardSubtitle:$('cardSubtitle').value.trim()||'العسل الحضرمي',totalStamps:total,giftText:gift,storeUrl,cardStart:$('cardStart').value,cardEnd:$('cardEnd').value,updatedAt:serverTimestamp()};\n await setDoc(doc(db,'settings','site'),settings,{merge:true});$('logoFile').value='';$('stampFile').value='';await loadSettings();toast('تم حفظ الإعدادات بنجاح')"
if old not in admin: print('save block not found')
else: admin=admin.replace(old,new)
(p/'admin.html').write_text(admin)

(p/'firestore.rules').write_text('''rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    function signedIn() { return request.auth != null; }\n    function isAdmin() { return signedIn() && (request.auth.uid == "DPOfZKEEhogjxeEgoKijthen7gZ2" || request.auth.token.email == "a777052026@gmail.com"); }\n    match /customers/{userId} {\n      allow read, create, update: if isAdmin() || (signedIn() && request.auth.uid == userId);\n      allow delete: if isAdmin();\n    }\n    match /settings/{settingId} {\n      allow read: if signedIn();\n      allow write: if isAdmin();\n    }\n  }\n}\n''')
(p/'storage.rules').write_text('''rules_version = '2';\nservice firebase.storage {\n  match /b/{bucket}/o {\n    match /admin-assets/{allPaths=**} {\n      allow read: if request.auth != null;\n      allow write: if request.auth != null && (request.auth.uid == "DPOfZKEEhogjxeEgoKijthen7gZ2" || request.auth.token.email == "a777052026@gmail.com");\n    }\n  }\n}\n''')
